Migration guide for eclipse 4.29
eclipse-platform/eclipse.platform.releng.aggregator pull request #1268
Opened 2023-08-24 10:25 UTC by subyssurendran666

Migration guide for Eclipse 4.29 from 4.28

2023-08-24 11:07 UTC, ktatavarthi requested changes

2023-08-24 11:07 UTC, ktatavarthi commented on eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml
> +<topic label="Migrating to Eclipse JDT 4.29 from 4.28">
Please keep the indentation as before

2023-08-24 11:07 UTC, ktatavarthi commented on eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml
>  		<topic label="FAQ"                             href="porting/4.28/faq.html" />
Also only 4 of the topics should be in the top level, when adding a new one, move the older one to the top of older docs.

2023-08-25 05:36 UTC, subyssurendran666 commented on eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml
> +<topic label="Migrating to Eclipse JDT 4.29 from 4.28">
Done

2023-08-25 05:36 UTC, subyssurendran666 commented on eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml
>  		<topic label="FAQ"                             href="porting/4.28/faq.html" />
Done

2023-08-25 05:37 UTC, subyssurendran666 commented on eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Porting.xml
> +	</topic>
Done

2023-08-30 06:06 UTC, ktatavarthi approved these changes

2023-08-30 06:58 UTC, merged

2023-09-01 06:21 UTC, jukzi commented
referenced org.eclipse.platform.doc.isv/porting/4.29/faq.html (and others)
is missing

see https://download.eclipse.org/eclipse/downloads/drops4/S-4.29RC2-202308302200/testresults/html/org.eclipse.ua.tests.doc_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

```

java.lang.AssertionError: Invalid link in "/org.eclipse.platform.doc.isv/topics_Porting.xml": porting/eclipse_4_29_porting_guide.html
Invalid link in "/org.eclipse.platform.doc.isv/topics_Porting.xml": porting/4.29/faq.html
Invalid link in "/org.eclipse.platform.doc.isv/topics_Porting.xml": porting/4.29/incompatibilities.html
Invalid link in "/org.eclipse.platform.doc.isv/topics_Porting.xml": porting/4.29/recommended.html

at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker.doAssert(TocLinkChecker.java:129)
at org.eclipse.ua.tests.doc.internal.linkchecker.TocLinkChecker.testPlatformIsvStatic(TocLinkChecker.java:84)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```