[Setup] Add JGit LFS to Platform Aggregator setup
eclipse-platform/eclipse.platform.releng.aggregator pull request #1719
Opened 2024-01-13 18:44 UTC by HannesWell

The eclipse.platform.swt sub-module contains Git LFS content. Therefore in order to fully pull it with EGit/JGit the LFS plugin is necessary.

@merks or should we just add it to the parent Platform project? Then it would not be necessary to have it in the SWT setup and the Platform Aggregator setup.
Having it installed is usually not a problem if not used.

@laeubi FYI

2024-01-13 19:26 UTC, merks commented
There is no harm in adding/installing it more generally.

2024-01-14 08:37 UTC, HannesWell commented
> There is no harm in adding/installing it more generally.

Moved it to the existing `Platform` P2 Director and renamed it to `Platform and Git LFS`. Or would you prefer to have two P2-Director tasks here?

2024-01-14 08:58 UTC, merks commented
> Or would you prefer to have two P2-Director tasks here?

Either way is fine.

2024-01-14 08:59 UTC, merks requested changes
Note that there is no need to specify an EGit site because if there is any Git Clone task, this will be added automatically:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/df2ea23d-10e7-4e86-937d-89cbab889762)

So probably better not to add it.

2024-01-14 09:06 UTC, HannesWell commented
> Note that there is no need to specify an EGit site because if there is any Git Clone task, this will be added automatically:

Thanks for the hint. I saw it in my setup that the EGit site is available but since I didn't found a P2 director in the parents I assumed it is due to my local user, workspace or installation setup. Didn't know or at least wasn't sure that the Git clone tasks adds it implicitly.

2024-01-14 11:47 UTC, HannesWell commented
@merks I assume you are now fine with this change, aren't you?

2024-01-14 13:06 UTC, merks approved these changes
Yes, looks good.

2024-01-14 13:18 UTC, merged