Add upstream ASM 9.3 to target-platform
eclipse-platform/eclipse.platform.releng.aggregator pull request #196
Opened 2022-04-06 14:35 UTC by mickaelistria

So bundles can start using it. Older references will be removed later
once all consumers have updated the necessary Required-Bundles or
feature.xml content.

See also eclipse-pde/eclipse.pde.ui#11

2022-04-06 14:40 UTC, vogella commented
Looks good. Maybe we should start using labels? Something like:
	  <location includeDependencyDepth="infinite" includeDependencyScopes="compile" includeSource="true" label="ASM dependencies" missingManifest="error" type="Maven">

2022-04-06 14:45 UTC, vogella commented
Example in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/197

2022-04-06 15:12 UTC, HannesWell commented on eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
> +		  <artifactId>asm-utils</artifactId>
shouldn't this be `asm-util` without an s?
https://search.maven.org/artifact/org.ow2.asm/asm-util/9.3/jar

2022-04-06 15:13 UTC, HannesWell commented on eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
> +		  <artifactId>asm-tree</artifactId>
This is already a compile-dependency of `org.ow2.asm:asm-util`.
I think it can therefore be removed.

2022-04-06 15:13 UTC, HannesWell commented on eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
> +		  <artifactId>asm</artifactId>
This is already a compile-dependency of `org.ow2.asm:asm-util`.
I think it can therefore be removed.

2022-04-06 15:14 UTC, HannesWell commented on eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
> +		  <artifactId>asm-analysis</artifactId>
This is already a compile-dependency of `org.ow2.asm:asm-util`, too.

2022-04-06 15:15 UTC, HannesWell requested changes
As Lars suggested, grouping dependencies with labels sounds good.

Furthermore I think it would be good to use the new target-location attributes. They are written automatically once you have edited this target-file via the editor.

2022-04-06 15:48 UTC, HannesWell commented on eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
> +          <artifactId>asm</artifactId>
This could also be removed.
Or do you want to keep this for another reason?

2022-04-06 15:50 UTC, mickaelistria commented on eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
> +          <artifactId>asm</artifactId>
I started by mimicking the list of bundles from Orbit. I didn't audit what can be removed or not according to the dependency tree. But OK, I'll remove it.

2022-04-06 16:10 UTC, HannesWell approved these changes
LGTM.

2022-04-08 15:45 UTC, vogella approved these changes

2022-04-08 17:29 UTC, merged