How to use junit.jupiter Extensions in OSGi and plain java
eclipse-platform/eclipse.platform.releng.aggregator pull request #2510
Opened 2024-11-04 09:43 UTC by jukzi

2024-11-04 09:44 UTC, akurtakov commented on eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/services/LoggingTestExtension.java
> +package org.eclipse.test.services;
Missing license header

2024-11-04 09:45 UTC, jukzi commented
@Bananeweizen is this snippet basically what we discussed? Or am i missing something?

2024-11-04 10:57 UTC, Bananeweizen commented
@jukzi The mechanics look good to me. I haven't used the properties file yet (because we have all properties in the maven invocation for our company projects), therefore I can't judge that file. Also if you just want the timing as such, https://github.com/junit-team/junit5/blob/main/documentation/src/test/java/example/timing/TimingExtension.java would be available.

You also had mentioned a problem with TestSuites, e.g. forgetting to add new tests to existing suites, or re-running suites taking long time? Can you eventually point me to some existing discussion or bug about that? I run all the tests in our company without using any suites, therefore I can't really remember anymore which problem that was...

2024-11-04 11:02 UTC, Bananeweizen commented on eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/services/LoggingTestExtension.java
> +		Throwable t = context.getExecutionException().orElse(null);
that's the most simple way to judge the test outcome. alternatively you could also implement https://junit.org/junit5/docs/5.4.1/api/org/junit/jupiter/api/extension/TestWatcher.html, which gets notified on test results. Not sure what fits better for your case.

2024-11-04 11:04 UTC, jukzi commented
@Bananeweizen the main point is that somehow "junit.jupiter.extensions.autodetection.enabled=true" has to be set (you did not mention that) otherwise it does not work.

regarding TestSuite see:
https://github.com/eclipse-platform/eclipse.platform.ui/pull/2391 and
https://www.eclipse.org/lists/jdt-dev/threads.html#02401

2024-11-04 11:09 UTC, jukzi commented on eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/services/LoggingTestExtension.java
> +package org.eclipse.test.services;
thanks, fixed

2024-11-04 18:13 UTC, HannesWell requested changes

2024-11-04 18:13 UTC, HannesWell commented on eclipse.platform.releng/bundles/org.eclipse.test/META-INF/MANIFEST.MF
> + org.apache.aries.spifly.dynamic.bundle,
You should not the bundle `org.apache.aries.spifly.dynamic.bundle` by it's name.

If you want to make sure that this bundle properly registers it's provided service at the OSGi service loader mediator is present then you should instead register the extension as provided Java service:
```
Require-Capability: osgi.extender;filter:="(&(osgi.extender=osgi.serviceloader.registrar)
 (version>=1.0.0)(!(version>=2.0.0)))"
Provide-Capability: osgi.serviceloader;osgi.serviceloader=org.junit.jupiter.api.extension.Extension
```
Maybe this also helps with your registration issue, because without these changes the extension is basically invisible in an OSGi runtime. Of course this requires also that the JUnit bundles are configured correspondingly for OSGi runtimes as service consumer.
For reference see
https://aries.apache.org/documentation/modules/spi-fly.html#specconf
https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.loader.html

2024-12-11 23:31 UTC, HannesWell commented on eclipse.platform.releng/bundles/org.eclipse.test/META-INF/MANIFEST.MF
> + org.apache.aries.spifly.dynamic.bundle,
The issue you mentioned in 
> the main point is that somehow "junit.jupiter.extensions.autodetection.enabled=true" has to be set (you did not mention that) otherwise it does not work.

> I would like to understand what is changed/improved if i would use the "Capability" thing instead. Especially how that would work in an non-osgi environment like SWT tests.

To summarize it in short: It makes the Java service loader work in OSGi runtimes, where it does not work out of the box due to classloader separation of bundles. Additionally you have to make sure that a provider is auto-started by the app or product.
In non-OSGi environments like SWT tests the java Service-Loader works out of the box because the app has one flat classpath.

In general I'm not aware of any situation where a bundle should require `org.apache.aries.spifly.dynamic.bundle` or one of it's packages directly.

If you point me to your exact use-case I can try to help making it work.

2024-12-12 08:16 UTC, jukzi commented on eclipse.platform.releng/bundles/org.eclipse.test/META-INF/MANIFEST.MF
> + org.apache.aries.spifly.dynamic.bundle,
The general idea is to surround all junit tests in the I-Build with the same logging and checks. However as far as i have tested it seems to work on junit5 tests only and still most tests are 3 or 4. Thats where i am stuck with this experiment.

2024-12-12 08:32 UTC, laeubi commented on eclipse.platform.releng/bundles/org.eclipse.test/META-INF/MANIFEST.MF
> + org.apache.aries.spifly.dynamic.bundle,
> In general I'm not aware of any situation where a bundle should require org.apache.aries.spifly.dynamic.bundle or one of it's packages directly.

I think we more want a require capability then here this will require/pull in that automatically.

2025-03-12 07:44 UTC, akurtakov commented
Does anyone plan to finish this one or we should close it?

2025-03-13 07:57 UTC, closed without merging