Add documentation for the added eclipse.appName System Property
eclipse-platform/eclipse.platform.releng.aggregator pull request #2663
Opened 2024-12-16 08:42 UTC by azoitl

The eclipse.appName sytem property allows users to specify on the command line the appName to be used for a specific Eclipse instance. The appName Display property is used by window managers and desktop environments for identification and grouping. This is helpful to distinguish Eclipse instances (e.g., JDT vs CDT) as per default these all are using the same identifier.

Eclipse UI PR:
https://github.com/eclipse-platform/eclipse.platform.ui/pull/2631 
Root Issue: eclipse-packaging/packages#253

2024-12-16 15:27 UTC, jonahgraham reviewed
Once https://github.com/eclipse-platform/eclipse.platform.ui/pull/2631 is done this LGTM

2024-12-16 15:52 UTC, merks requested changes
I minor typo/grammar fix.

2024-12-16 15:52 UTC, merks commented on eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html
> +  <dd>allows to set the application name with which Eclipse is regsitered at the operating system. This option is helpful to
```suggestion
  <dd>allows to set the application name with which Eclipse is registered in the operating system. This option is helpful to
```

2025-03-06 21:57 UTC, akurtakov commented
@merks Is this good with you now?

2025-03-07 13:28 UTC, merks commented on eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html
> +  <dd>allows to set the application name with which Eclipse is registered in the operating system. This option is helpful to
Looks good but this should probably start with a capital letter like line 317 does, right?

2025-03-11 06:07 UTC, akurtakov commented on eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html
> +  <dd>allows to set the application name with which Eclipse is registered in the operating system. This option is helpful to
<dd>Allows to set the application name with which Eclipse is registered in the operating system. This option is helpful to

2025-03-18 13:48 UTC, merged

2025-03-18 14:56 UTC, akurtakov commented on eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html
> +  <dd>allows to set the application name with which Eclipse is registered in the operating system. This option is helpful to
NP, it happens to everyone nowadays.