add preference help for custom folding regions
eclipse-platform/eclipse.platform.releng.aggregator pull request #2703
Opened 2024-12-25 19:50 UTC by danthe1st

This PR contains the help page update for https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1825.

2024-12-27 10:20 UTC, BeckerWdf requested changes

2024-12-27 10:20 UTC, BeckerWdf commented on eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/reference/preferences/java/editor/ref-preferences-folding.htm
> +<p>
I would not add the screenshot here. I don't see that it's done on other help pages.
This is more something that should go into the "New and Noteworthy" entry for this feature.

2025-01-06 10:01 UTC, mickaelistria commented
@danthe1st this is still marked as draft. Is there anything pending on your end preventing a merge?

2025-01-06 10:13 UTC, danthe1st commented
> this is still marked as draft. Is there anything pending on your end preventing a merge?

The PR introducing this feature is still open: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1825

Until the feature is actually merged, I don't think there's a point in merging this PR.

2025-03-07 13:27 UTC, akurtakov commented
@danthe1st Now that it has been merged in jdt, please fix the merge conflict .
@jjohnstn Would you please review that the content matches what was merged in jdt?

2025-03-07 17:11 UTC, jjohnstn commented
@akurtakov Will do

2025-03-10 21:00 UTC, jjohnstn commented
Hi @akurtakov The content being added is correct and matches the new options/behavior.

2025-03-12 11:42 UTC, merged